//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvd_Lession11Db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NvdCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NvdCategory()
        {
            this.NvdProducts = new HashSet<NvdProduct>();
        }

        [Display(Name ="Mã danh mục")]
        public int NvdCateID { get; set; }
        [Display(Name = "Tên danh mục")]

        public string NvdCateName { get; set; }
        [Display(Name = "Trạng thái")]

        public Nullable<bool> NvdStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NvdProduct> NvdProducts { get; set; }
    }
}
