//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvd_Lession11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvdProduct
    {
        public string NvdID2210900016 { get; set; }
        public string NvdProName { get; set; }
        public Nullable<int> NvdQty { get; set; }
        public Nullable<double> NvdPrice { get; set; }
        public Nullable<int> NvdCateID { get; set; }
        public Nullable<bool> NvdActive { get; set; }
    
        public virtual NvdCategory NvdCategory { get; set; }
    }
}
